export { default as gb } from './gb.svelte'
export { default as us } from './us.svelte'
export { default as au } from './au.svelte'
export { default as ca } from './ca.svelte'
export { default as fr } from './fr.svelte'
export { default as es } from './es.svelte'
export { default as de } from './de.svelte'
